export const statesAbbrLookup = {
  AL: { text: "Alabama", slug: "alabama" },
  AK: { text: "Alaska", slug: "alaska" },
  AZ: { text: "Arizona", slug: "arizona" },
  AR: { text: "Arkansas", slug: "arkansas" },
  CA: { text: "California", slug: "california" },
  CO: { text: "Colorado", slug: "colorado" },
  CT: { text: "Connecticut", slug: "connecticut" },
  DE: { text: "Delaware", slug: "delaware" },
  FL: { text: "Florida", slug: "florida" },
  GA: { text: "Georgia", slug: "georgia" },
  HI: { text: "Hawaii", slug: "hawaii" },
  ID: { text: "Idaho", slug: "idaho" },
  IL: { text: "Illinois", slug: "illinois" },
  IN: { text: "Indiana", slug: "indiana" },
  IA: { text: "Iowa", slug: "iowa" },
  KS: { text: "Kansas", slug: "kansas" },
  KY: { text: "Kentucky", slug: "kentucky" },
  LA: { text: "Louisiana", slug: "louisiana" },
  ME: { text: "Maine", slug: "maine" },
  MD: { text: "Maryland", slug: "maryland" },
  MA: { text: "Massachusetts", slug: "massachusetts" },
  MI: { text: "Michigan", slug: "michigan" },
  MN: { text: "Minnesota", slug: "minnesota" },
  MS: { text: "Mississippi", slug: "mississippi" },
  MO: { text: "Missouri", slug: "missouri" },
  MT: { text: "Montana", slug: "montana" },
  NE: { text: "Nebraska", slug: "nebraska" },
  NV: { text: "Nevada", slug: "nevada" },
  NH: { text: "New Hampshire", slug: "new_hampshire" },
  NJ: { text: "New Jersey", slug: "new_jersey" },
  NM: { text: "New Mexico", slug: "new_mexico" },
  NY: { text: "New York", slug: "new_york" },
  NC: { text: "North Carolina", slug: "north_carolina" },
  ND: { text: "North Dakota", slug: "north_dakota" },
  OH: { text: "Ohio", slug: "ohio" },
  OK: { text: "Oklahoma", slug: "oklahoma" },
  OR: { text: "Oregon", slug: "oregon" },
  PA: { text: "Pennsylvania", slug: "pennsylvania" },
  RI: { text: "Rhode Island", slug: "rhode_island" },
  SC: { text: "South Carolina", slug: "south_carolina" },
  SD: { text: "South Dakota", slug: "south_dakota" },
  TN: { text: "Tennessee", slug: "tennessee" },
  TX: { text: "Texas", slug: "texas" },
  UT: { text: "Utah", slug: "utah" },
  VT: { text: "Vermont", slug: "vermont" },
  VA: { text: "Virginia", slug: "virginia" },
  WA: { text: "Washington", slug: "washington" },
  WV: { text: "West Virginia", slug: "west_virginia" },
  WI: { text: "Wisconsin", slug: "wisconsin" },
  WY: { text: "Wyoming", slug: "wyoming" },
  DC: { text: "District of Columbia", slug: "district_of_columbia" },
};

export const slugToAbbr = {
  alabama: "AL",
  alaska: "AK",
  arizona: "AZ",
  arkansas: "AR",
  california: "CA",
  colorado: "CO",
  connecticut: "CT",
  delaware: "DE",
  florida: "FL",
  georgia: "GA",
  hawaii: "HI",
  idaho: "ID",
  illinois: "IL",
  indiana: "IN",
  iowa: "IA",
  kansas: "KS",
  kentucky: "KY",
  louisiana: "LA",
  maine: "ME",
  maryland: "MD",
  massachusetts: "MA",
  michigan: "MI",
  minnesota: "MN",
  mississippi: "MS",
  missouri: "MO",
  montana: "MT",
  nebraska: "NE",
  nevada: "NV",
  new_hampshire: "NH",
  new_jersey: "NJ",
  new_mexico: "NM",
  new_york: "NY",
  north_carolina: "NC",
  north_dakota: "ND",
  ohio: "OH",
  oklahoma: "OK",
  oregon: "OR",
  pennsylvania: "PA",
  rhode_island: "RI",
  south_carolina: "SC",
  south_dakota: "SD",
  tennessee: "TN",
  texas: "TX",
  utah: "UT",
  vermont: "VT",
  virginia: "VA",
  washington: "WA",
  west_virginia: "WV",
  wisconsin: "WI",
  wyoming: "WY",
  district_of_columbia: "DC",
};
